name: lameta-unofficial
title: laMETA
version: 2.0.19-beta
base: core18 # highest available for nodejs/yarn
summary: Lameta is a metadata tool to help with organising collections of files.
description: |
  Lameta is mainly aimed at collections made in the course of documenting language, music, and other cultural expressions.

  Lameta greatly simplifies management of collections and makes the archiving process straightforward and painless for field workers. 

  Hatton, John, Gary Holton, Mandana Seyfeddinipur, Nick Thieberger. 2021. Lameta [software] https://github.com/onset/laMETA/releases
grade: devel
confinement: devmode
architectures:
  - amd64
apps:
  lameta-unofficial:
    extensions: [gnome-3-34]
    command: lameta
    plugs:
      - audio-playback
      - home
      - network
      - udisks2

parts:
  lameta:
    plugin: nodejs
    nodejs-version: 8.10.0
    # nodejs-yarn-version: ???
    source: https://github.com/onset/lameta/archive/refs/tags/v2.0.19-beta.tar.gz
    override-build: |
      # Add yarn GPG key and repo.
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      apt-get update
      apt-get install yarn
      yarn
      yarn dev
      yarn package
