name: lameta-unofficial
title: laMETA
version: 2.0.19-beta
base: core22
summary: Lameta is a metadata tool to help with organising collections of files.
description: |
  Lameta is mainly aimed at collections made in the course of documenting language, music, and other cultural expressions.

  Lameta greatly simplifies management of collections and makes the archiving process straightforward and painless for field workers. 

  Hatton, John, Gary Holton, Mandana Seyfeddinipur, Nick Thieberger. 2021. Lameta [software] https://github.com/onset/laMETA/releases
grade: devel
confinement: devmode
architectures:
  - amd64
apps:
  lameta-unofficial:
    extensions: [gnome]
    command: lameta
    plugs:
      - audio-playback
      - home
      - network
      - udisks2

parts:
  lameta:
    plugin: npm
    npm-include-node: true
    npm-node-version: 8.10.0
    source: https://github.com/onset/lameta/archive/refs/tags/v2.0.19-beta.tar.gz
    override-build: |
      npm pkg set 'name="laMETA"'
      snapcraft build